// src/app/projects/project/project.component.ts
import { Component, Input } from '@angular/core';
import { Project } from '../../models/Project';

@Component({
  selector: 'app-project',
  imports: [],
  templateUrl: './project.component.html',
  styleUrls: ['./project.component.scss', '../projects.component.scss']
})
export class ProjectComponent {
  @Input() project?: Project;
}

<div class="project">
    <a class="project-links" [href]="project?.link" target="_blank" rel="noreferrer">
      <img [src]="project?.src" [alt]="project?.name" class="project-img" priority={true} />
      <div class="project-img-label text-center">{{project?.name}}</div>
    </a>
    <p class="project-description text-center">{{project?.description}}</p>
</div>

// src/components/projects/Project.tsx

const Project = (props: {obj: {src: string, link: string, name: string, description: string}}) => {
    const {src, link, name, description} = props.obj;

    return (
        <div className="project">
          <a className="project-links" href={link} target="_blank" rel="noreferrer">
            <img src={src} alt={name} className="project-img" />
            <div className="project-img-label text-center">{name}</div>
          </a>
          <p className="project-description text-center">{description}</p>
        </div>
    )
}

export default Project;
