// src/components/about-me/sub-components/Education.tsx
import '../../../css/about-me/sub-components/Education.css';

const Education = (props: {}) => {
    return (
        <div id="edu-section">
            <h2 id="edu-title" className="section-title">Education</h2>
            <h3 id="school-name"><b>Southern Utah University</b>,    2017-2020</h3>
            <p>
                BS in Applied Mathematics, <em>summa cum laude</em>
            </p>
            <ul id="edu-list">
                <li>Minors in Computer Science and Finance</li>
                <li>Coursework in Data Structures and Algorithms, Object-Oriented Programming, and Software Engineering Principles. </li>
            </ul>
        </div>
    )
}

export default Education;

// src/app/about-me/education/education.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-education',
  imports: [],
  templateUrl: './education.component.html',
  styleUrl: './education.component.scss'
})
export class EducationComponent {

}

<div id="edu-section">
    <h2 id="edu-title" class="section-title">Education</h2>
    <h3 id="school-name"><b>Southern Utah University</b>,    2017-2020</h3>
    <p>
        BS in Applied Mathematics, <em>summa cum laude</em>
    </p>
    <ul id="edu-list">
        <li>Minors in Computer Science and Finance</li>
        <li>Coursework in Data Structures and Algorithms, Object-Oriented Programming, and Software Engineering Principles. </li>
    </ul>
</div>
