// src/app/about-me/page.tsx
import Link from 'next/link';
import '../css/about-me/AboutMe.css'
import ContactMe from './components/ContactMe';
import Education from './components/Education';
import Technology from './components/Technology';

const AboutMe = (props: {}) => {
    return (
        <div>
            <div id="profile-pic"></div>

            <div id="about-me" className="text-center">
                <h1 id="about-me-title">About Me</h1>
                <p className="text-left about-me-summary">I am currently working as a Backend Engineer at Addepar. I have
                a strong background in mathematics and a passion for problem-solving.
                I thrive on the challenge of learning new technologies quickly and strive
                to continually improve my abilities as a developer.
                In my free time, I enjoy playing the guitar, reading, and spending time with my wife and our two cats.
                <br />
                <br />
                As a seasoned Software Engineer based in Salt Lake City, UT, I bring a wealth of technical expertise, a strong work ethic, and a passion for software development to every project I undertake. With a focus on enhancing team success, I excel in meticulous work, demonstrate keen attention to detail, and leverage outstanding organizational abilities. Proficient in a variety of programming languages including Java, Python, C++, SQL, and TypeScript (React, Node.js, Express), I am well-versed in object-oriented programming and software design principles.
                <br />
                <br />
                My journey with coding began about 10 years ago when I took a Web Programming class while still in high school in Colorado.
                I was immediately intrigued. I created a simple Snake Game and a few simple single-page websites.
                However, I soon after moved to Utah and the high school I attended there didn&#39;t have a strong computer science program.
                My focus moved to other things and the skills I had gained began to fade.
                <br />
                <br />
                When I began college at Southern Utah University in 2017, I decided to take an introductory computer science course that taught the basics of Java.
                My passion for programming was rekindled and I decided to pursue a Computer Science minor. I took courses in Data Structures and Algorithms, Foundations of Computation Theory, C++ Programming, and the Software Development Life Cycle.
                My education at SUU allowed me to gain a strong basis in the fundamentals of computer science.
                <br />
                <br />
                Since graduating from SUU in December 2020, I have dedicated free time each week to strengthening my coding skills and learning new technologies.
                I have completed certifications through FreeCodeCamp in Responsive Web Design, JavaScript Algorithms and Data Structures, Front End Development
                Libraries, and APIs and Microservices. I have also completed the Backend Engineer Career Path through Codecademy to increase my abilities working on the back end.
                <br />
                <br />
                I am committed to ongoing learning and advancement in the rapidly evolving software development landscape, fueled by a genuine passion for the field.
                Please check out my projects <Link href="/projects">here</Link> and let me know what you think!
                </p>            
            </div>

            <Education />
            <Technology />
            <ContactMe />

        </div>
    )
}

export default AboutMe;

// src/app/about-me/about-me.component.ts
import { Component } from '@angular/core';
import { EducationComponent } from "./education/education.component";
import { TechnologyComponent } from "./technology/technology.component";
import { ContactMeComponent } from "./contact-me/contact-me.component";

@Component({
  selector: 'app-about-me',
  imports: [EducationComponent, TechnologyComponent, ContactMeComponent],
  templateUrl: './about-me.component.html',
  styleUrl: './about-me.component.scss'
})
export class AboutMeComponent {

}

<div id="about-me-page">
    <div id="profile-pic"></div>

    <div id="about-me" class="text-center">
        <h1 id="about-me-title">About Me</h1>
        <p class="text-left about-me-summary">I am currently working as a Backend Engineer at Addepar. I have
        a strong background in mathematics and a passion for problem-solving.
        I thrive on the challenge of learning new technologies quickly and strive
        to continually improve my abilities as a developer.
        In my free time, I enjoy playing the guitar, reading, and spending time with my wife and our two cats.
        <br />
        <br />
        As a seasoned Software Engineer based in Salt Lake City, UT, I bring a wealth of technical expertise, a strong work ethic, and a passion for software development to every project I undertake. With a focus on enhancing team success, I excel in meticulous work, demonstrate keen attention to detail, and leverage outstanding organizational abilities. Proficient in a variety of programming languages including Java, Python, C++, SQL, and TypeScript (React, Node.js, Express), I am well-versed in object-oriented programming and software design principles.
        <br />
        <br />
        My journey with coding began about 10 years ago when I took a Web Programming class while still in high school in Colorado.
        I was immediately intrigued. I created a simple Snake Game and a few simple single-page websites.
        However, I soon after moved to Utah and the high school I attended there didn&#39;t have a strong computer science program.
        My focus moved to other things and the skills I had gained began to fade.
        <br />
        <br />
        When I began college at Southern Utah University in 2017, I decided to take an introductory computer science course that taught the basics of Java.
        My passion for programming was rekindled and I decided to pursue a Computer Science minor. I took courses in Data Structures and Algorithms, Foundations of Computation Theory, C++ Programming, and the Software Development Life Cycle.
        My education at SUU allowed me to gain a strong basis in the fundamentals of computer science.
        <br />
        <br />
        Since graduating from SUU in December 2020, I have dedicated free time each week to strengthening my coding skills and learning new technologies.
        I have completed certifications through FreeCodeCamp in Responsive Web Design, JavaScript Algorithms and Data Structures, Front End Development
        Libraries, and APIs and Microservices. I have also completed the Backend Engineer Career Path through Codecademy to increase my abilities working on the back end.
        <br />
        <br />
        I am committed to ongoing learning and advancement in the rapidly evolving software development landscape, fueled by a genuine passion for the field.
        Please check out my projects <a routerLink="/projects" routerLinkActive="active">here</a> and let me know what you think!
        </p>            
    </div>

    <app-education />
    <app-technology />
    <app-contact-me />

</div>
