// src/app/about-me/contact-me/contact-me.component.ts
import { Component, OnInit } from '@angular/core';
import { ContactLinkComponent } from "./contact-link/contact-link.component";
import { LinkData } from '../../models/LinkData';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-contact-me',
  imports: [ContactLinkComponent, CommonModule],
  templateUrl: './contact-me.component.html',
  styleUrl: './contact-me.component.scss'
})
export class ContactMeComponent implements OnInit {
  links: LinkData[] = [
    {
        link: "https://andrewccartwright.github.io/interactive-resume/",
        text: "Resume"
    },
    {
        link: "mailto: drew.c.cartwright@gmail.com",
        text: "Email"
    },
    {
        link: "https://www.linkedin.com/in/andrew-cartwright-8b13b0134",
        text: "LinkedIn"
    },
    {
        link: "https://github.com/andrewccartwright",
        text: "GitHub"
    }
  ]

  ngOnInit(): void {

  }
}

<div id="contact-me-section" class="text-center">
    <h2 id="contact-me-title">Contact Me</h2>

    <app-contact-link *ngFor="let link of links" [linkData]="link"></app-contact-link>
</div>

// src/components/about-me/sub-components/ContactMe.tsx
import '../../../css/about-me/sub-components/ContactMe.css';

const ContactMe = (props: {}) => {
    return (
        <div id="contact-me-section" className="text-center">
            <h2 id="contact-me-title">Contact Me</h2>

            <p> Resume: <a href="https://andrewccartwright.github.io/interactive-resume/" target="_blank">Interactive Resume</a></p>
            <p> Email: <a href="mailto: drew.c.cartwright@gmail.com" data-rel="external" target="_blank">drew.c.cartwright@gmail.com</a></p>
            <p>LinkedIn: <a href="https://www.linkedin.com/in/andrew-cartwright-8b13b0134" target="_blank">linkedin.com/in/andrew-cartwright-8b13b0134</a></p>
            <p>GitHub: <a href="https://github.com/andrewccartwright" target="_blank">github.com/andrewccartwright</a></p>
        </div>
    )
}

export default ContactMe;
