// src/app/about-me/components/ContactMe.tsx
import '../../css/about-me/ContactMe.css';
import ContactLink from './ContactLink';

const ContactMe = (props: {}) => {
    const links: LinkData[] = [
        {
            link: "https://andrewccartwright.github.io/interactive-resume/",
            text: "Resume"
        },
        {
            link: "mailto: drew.c.cartwright@gmail.com",
            text: "Email"
        },
        {
            link: "https://www.linkedin.com/in/andrew-cartwright-8b13b0134",
            text: "LinkedIn"
        },
        {
            link: "https://github.com/andrewccartwright",
            text: "GitHub"
        }
    ]


    return (
        <div id="contact-me-section" className="text-center">
            <h2 id="contact-me-title">Contact Me</h2>

            {
                links.map((data, i) => {
                    return <ContactLink data={data} key={i} />
                })
            }
        </div>
    )
}

export default ContactMe;

// src/app/about-me/contact-me/contact-me.component.ts
import { Component, OnInit } from '@angular/core';
import { ContactLinkComponent } from "./contact-link/contact-link.component";
import { LinkData } from '../../models/LinkData';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-contact-me',
  imports: [ContactLinkComponent, CommonModule],
  templateUrl: './contact-me.component.html',
  styleUrl: './contact-me.component.scss'
})
export class ContactMeComponent implements OnInit {
  links: LinkData[] = [
    {
        link: "https://andrewccartwright.github.io/interactive-resume/",
        text: "Resume"
    },
    {
        link: "mailto: drew.c.cartwright@gmail.com",
        text: "Email"
    },
    {
        link: "https://www.linkedin.com/in/andrew-cartwright-8b13b0134",
        text: "LinkedIn"
    },
    {
        link: "https://github.com/andrewccartwright",
        text: "GitHub"
    }
  ]

  ngOnInit(): void {

  }
}

<div id="contact-me-section" class="text-center">
    <h2 id="contact-me-title">Contact Me</h2>

    <app-contact-link *ngFor="let link of links" [linkData]="link"></app-contact-link>
</div>
