// src/app/about-me/contact-me/contact-link/contact-link.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { LinkData } from '../../../models/LinkData';

@Component({
  selector: 'app-contact-link',
  imports: [],
  templateUrl: './contact-link.component.html',
  styleUrls: ['./contact-link.component.scss', '../contact-me.component.scss']
})
export class ContactLinkComponent implements OnInit {
  @Input() linkData?: LinkData;

  ngOnInit(): void {
      
  }
}

<a class="contact-links" [href]="linkData?.link" target="_blank" rel="noreferrer">
    <div class="contact-link-container">
        {{linkData?.text}}
    </div>
</a>

// src/app/about-me/components/ContactLink.tsx
const ContactLink = (props: {data: LinkData}) => {
    const { data } = props;

    return (
        <a className="contact-links" href={data.link} target="_blank" rel="noreferrer">
            <div className="contact-link-container">
                {data.text}
            </div>
        </a>
    )
}

export default ContactLink;
