// src/app/about-me/components/TechImage.tsx
import Image, { StaticImageData } from "next/image";

const TechImage = (props: {obj: {src: StaticImageData, alt: string, label: string}}) => {
    const src = props.obj.src;
    const alt = props.obj.alt;
    const label = props.obj.label;

    return (
        <div className="col-sm img-div">
            <Image src={src} alt={alt} className="img-responsive" priority={true} />
            <p className="img-label">{label}</p>
        </div>
    )    
}

export default TechImage;

// src/app/about-me/technology/tech-image/tech-image.component.ts
import { Component, Inject, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-tech-image',
  imports: [],
  templateUrl: './tech-image.component.html',
  styleUrls: ['./tech-image.component.scss', '../technology.component.scss']
})
export class TechImageComponent implements OnInit {
  @Input() src: string = '';
  @Input() alt: string = '';
  @Input() label: string = '';

  ngOnInit(): void {
    
  }

}

<div class="col-sm img-div">
    <img [src]="src" [alt]="alt" class="img-responsive" priority={true} />
    <p class="img-label">{{label}}</p>
</div>
