// src/app/components/Navbar.tsx
'use client'

import Link from 'next/link';
import '../css/Navbar.css';

const Navbar = (props: {}) => {
    const onClick = () => {
        const body = document.getElementById('body');

        if (body != null) {
            body.style.background = '#FFFFFF';
        }
    }

    return (
        <div id='nav-bar' className="text-center">
            <div id="links-section">
                <Link id="welcome-link" className="nav-links" href="/">WELCOME</Link>
                <Link id="projects-link" className="nav-links" href="/projects" onClick={onClick}>PROJECTS</Link>
                <Link id="about-me-link" className="nav-links" href="/about-me" onClick={onClick}>ABOUT ME</Link>    
            </div>
        </div>
    )
}   

export default Navbar;

// src/app/nav-bar/nav-bar.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-nav-bar',
  imports: [RouterLink, RouterLinkActive],
  templateUrl: './nav-bar.component.html',
  styleUrl: './nav-bar.component.scss'
})
export class NavBarComponent {

}

<div id='nav-bar' class="text-center">
    <div id="links-section">
        <a id="welcome-link" class="nav-links" routerLink="/" routerLinkActive="active">WELCOME</a>
        <a id="projects-link" class="nav-links" routerLink="/projects" routerLinkActive="active">PROJECTS</a>
        <a id="about-me-link" class="nav-links" routerLink="/about-me" routerLinkActive="active">ABOUT ME</a>    
    </div>
</div>
