// src/app/projects/project/project.component.ts
import { Component, Input } from '@angular/core';
import { Project } from '../../models/Project';

@Component({
  selector: 'app-project',
  imports: [],
  templateUrl: './project.component.html',
  styleUrls: ['./project.component.scss', '../projects.component.scss']
})
export class ProjectComponent {
  @Input() project?: Project;
}

<div class="project">
    <a class="project-links" [href]="project?.link" target="_blank" rel="noreferrer">
      <img [src]="project?.src" [alt]="project?.name" class="project-img" priority={true} />
      <div class="project-img-label text-center">{{project?.name}}</div>
    </a>
    <p class="project-description text-center">{{project?.description}}</p>
</div>

// src/app/projects/components/Project.tsx
import Image from "next/image";
import ProjectData from "./ProjectData";

const Project = (props: {project: ProjectData}) => {
    const { src, name, link, description } = props.project;

    return (
        <div className="project">
          <a className="project-links" href={link} target="_blank" rel="noreferrer">
            <Image src={src} alt={name} className="project-img" priority={true} />
            <div className="project-img-label text-center">{name}</div>
          </a>
          <p className="project-description text-center">{description}</p>

          { link === 'https://andrewccartwright.github.io/quasigroups' && 
            <p> You can read more about quasigroups&nbsp;
              <a href='https://en.wikipedia.org/wiki/Quasigroup#:~:text=In%20mathematics%2C%20especially%20in%20abstract,not%20have%20an%20identity%20element.' target='_blank' rel="noreferrer">
                here
              </a>
              .
            </p>
            
          }
        </div>
    )
}

export default Project;
